name: Nest

on: [push, pull_request]
  
jobs:
  package:
    name: Package, bundle, and upload
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: benjlevesque/short-sha@v1.2
        id: short-sha
        with:
          length: 6

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.1
        with:
          node-version: '16'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install modules
        run: yarn install --frozen-lockfile

      - name: Build, package, bundle, and clear
        env:
          BUILD_ENVIRONMENT: cit
          COMMIT_IDENTIFIER: ${{ github.sha }}
        run: yarn bundle:release

      - name: Upload artifact to S3
        env:
          AWS_REGION: us-east-1
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp bundle.zip s3://${{ secrets.AWS_S3_LAMBDA_BUCKET }}/commits/${{ github.sha }}.zip
